// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package database

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (
    id, session_id, role, content, parent_id, tokens_used, model, finish_reason, metadata
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMessageParams struct {
	ID           string  `json:"id"`
	SessionID    string  `json:"session_id"`
	Role         string  `json:"role"`
	Content      string  `json:"content"`
	ParentID     *string `json:"parent_id"`
	TokensUsed   *int64  `json:"tokens_used"`
	Model        *string `json:"model"`
	FinishReason *string `json:"finish_reason"`
	Metadata     *string `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ParentID,
		arg.TokensUsed,
		arg.Model,
		arg.FinishReason,
		arg.Metadata,
	)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, id)
	return err
}

const deleteMessagesBySession = `-- name: DeleteMessagesBySession :exec
DELETE FROM messages
WHERE session_id = ?
`

func (q *Queries) DeleteMessagesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesBySession, sessionID)
	return err
}

const getConversationThread = `-- name: GetConversationThread :many
WITH RECURSIVE thread AS (
    -- Base case: start with the specified message
    SELECT messages.id, messages.session_id, messages.role, messages.content, messages.timestamp, messages.parent_id, messages.tokens_used, messages.model, messages.finish_reason, messages.metadata, 0 as depth
    FROM messages
    WHERE messages.id = ?

    UNION ALL

    -- Recursive case: get all ancestors
    SELECT m.id, m.session_id, m.role, m.content, m.timestamp, m.parent_id, m.tokens_used, m.model, m.finish_reason, m.metadata, t.depth + 1
    FROM messages m
    INNER JOIN thread t ON m.id = t.parent_id
)
SELECT thread.id, thread.session_id, thread.role, thread.content, thread.timestamp, thread.parent_id, thread.tokens_used, thread.model, thread.finish_reason, thread.metadata
FROM thread
ORDER BY thread.depth DESC, thread.timestamp ASC
`

type GetConversationThreadRow struct {
	ID           string  `json:"id"`
	SessionID    string  `json:"session_id"`
	Role         string  `json:"role"`
	Content      string  `json:"content"`
	Timestamp    string  `json:"timestamp"`
	ParentID     *string `json:"parent_id"`
	TokensUsed   *int64  `json:"tokens_used"`
	Model        *string `json:"model"`
	FinishReason *string `json:"finish_reason"`
	Metadata     *string `json:"metadata"`
}

func (q *Queries) GetConversationThread(ctx context.Context, id string) ([]GetConversationThreadRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationThread, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConversationThreadRow{}
	for rows.Next() {
		var i GetConversationThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMessage = `-- name: GetLatestMessage :one
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ?
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestMessage(ctx context.Context, sessionID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLatestMessage, sessionID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Timestamp,
		&i.ParentID,
		&i.TokensUsed,
		&i.Model,
		&i.FinishReason,
		&i.Metadata,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.Timestamp,
		&i.ParentID,
		&i.TokensUsed,
		&i.Model,
		&i.FinishReason,
		&i.Metadata,
	)
	return i, err
}

const getMessageCount = `-- name: GetMessageCount :one
SELECT COUNT(*) as count
FROM messages
WHERE session_id = ?
`

func (q *Queries) GetMessageCount(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCount, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessageCountByRole = `-- name: GetMessageCountByRole :one
SELECT COUNT(*) as count
FROM messages
WHERE session_id = ? AND role = ?
`

type GetMessageCountByRoleParams struct {
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
}

func (q *Queries) GetMessageCountByRole(ctx context.Context, arg GetMessageCountByRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageCountByRole, arg.SessionID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMessagesByTimeRange = `-- name: GetMessagesByTimeRange :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ?
  AND timestamp >= ?
  AND timestamp <= ?
ORDER BY timestamp ASC
`

type GetMessagesByTimeRangeParams struct {
	SessionID   string `json:"session_id"`
	Timestamp   string `json:"timestamp"`
	Timestamp_2 string `json:"timestamp_2"`
}

func (q *Queries) GetMessagesByTimeRange(ctx context.Context, arg GetMessagesByTimeRangeParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByTimeRange, arg.SessionID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalTokensUsed = `-- name: GetTotalTokensUsed :one
SELECT COALESCE(SUM(tokens_used), 0) as total_tokens
FROM messages
WHERE session_id = ?
`

func (q *Queries) GetTotalTokensUsed(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalTokensUsed, sessionID)
	var total_tokens interface{}
	err := row.Scan(&total_tokens)
	return total_tokens, err
}

const listMessagesByParent = `-- name: ListMessagesByParent :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE parent_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) ListMessagesByParent(ctx context.Context, parentID *string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRole = `-- name: ListMessagesByRole :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ? AND role = ?
ORDER BY timestamp ASC
`

type ListMessagesByRoleParams struct {
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
}

func (q *Queries) ListMessagesByRole(ctx context.Context, arg ListMessagesByRoleParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRole, arg.SessionID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySessionPaginated = `-- name: ListMessagesBySessionPaginated :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type ListMessagesBySessionPaginatedParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySessionPaginated, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
SELECT id, session_id, role, content, timestamp, parent_id, tokens_used, model, finish_reason, metadata
FROM messages
WHERE session_id = ? AND content LIKE ?
ORDER BY timestamp DESC
LIMIT ? OFFSET ?
`

type SearchMessagesParams struct {
	SessionID string `json:"session_id"`
	Content   string `json:"content"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages,
		arg.SessionID,
		arg.Content,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.ParentID,
			&i.TokensUsed,
			&i.Model,
			&i.FinishReason,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET content = ?,
    tokens_used = ?,
    finish_reason = ?,
    metadata = ?
WHERE id = ?
`

type UpdateMessageParams struct {
	Content      string  `json:"content"`
	TokensUsed   *int64  `json:"tokens_used"`
	FinishReason *string `json:"finish_reason"`
	Metadata     *string `json:"metadata"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.ExecContext(ctx, updateMessage,
		arg.Content,
		arg.TokensUsed,
		arg.FinishReason,
		arg.Metadata,
		arg.ID,
	)
	return err
}
