// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package database

import (
	"context"
)

const deleteMetadata = `-- name: DeleteMetadata :exec
DELETE FROM metadata
WHERE key = ?
`

func (q *Queries) DeleteMetadata(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteMetadata, key)
	return err
}

const getMetadata = `-- name: GetMetadata :one
SELECT key, value, created_at, updated_at
FROM metadata
WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var i Metadata
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMetadata = `-- name: ListMetadata :many
SELECT key, value, created_at, updated_at
FROM metadata
ORDER BY key
`

func (q *Queries) ListMetadata(ctx context.Context) ([]Metadata, error) {
	rows, err := q.db.QueryContext(ctx, listMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Metadata{}
	for rows.Next() {
		var i Metadata
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const metadataExists = `-- name: MetadataExists :one
SELECT COUNT(*) > 0 as key_exists
FROM metadata
WHERE key = ?
`

func (q *Queries) MetadataExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, metadataExists, key)
	var key_exists bool
	err := row.Scan(&key_exists)
	return key_exists, err
}

const setMetadata = `-- name: SetMetadata :exec
INSERT OR REPLACE INTO metadata (key, value)
VALUES (?, ?)
`

type SetMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetMetadata(ctx context.Context, arg SetMetadataParams) error {
	_, err := q.db.ExecContext(ctx, setMetadata, arg.Key, arg.Value)
	return err
}
