// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Message struct {
	ID           string  `json:"id"`
	SessionID    string  `json:"session_id"`
	Role         string  `json:"role"`
	Content      string  `json:"content"`
	Timestamp    string  `json:"timestamp"`
	ParentID     *string `json:"parent_id"`
	TokensUsed   *int64  `json:"tokens_used"`
	Model        *string `json:"model"`
	FinishReason *string `json:"finish_reason"`
	Metadata     *string `json:"metadata"`
}

type Metadata struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Session struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	CreatedAt   string   `json:"created_at"`
	UpdatedAt   string   `json:"updated_at"`
	Status      string   `json:"status"`
	Model       *string  `json:"model"`
	Temperature *float64 `json:"temperature"`
	MaxTokens   *int64   `json:"max_tokens"`
	Settings    *string  `json:"settings"`
}

type ToolExecution struct {
	ID          string  `json:"id"`
	MessageID   string  `json:"message_id"`
	ToolName    string  `json:"tool_name"`
	Input       string  `json:"input"`
	Output      *string `json:"output"`
	Status      string  `json:"status"`
	Error       *string `json:"error"`
	StartedAt   string  `json:"started_at"`
	CompletedAt *string `json:"completed_at"`
	DurationMs  *int64  `json:"duration_ms"`
	RetryCount  int64   `json:"retry_count"`
	Metadata    *string `json:"metadata"`
}
