// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	ArchiveSession(ctx context.Context, id string) error
	CountSessions(ctx context.Context) (int64, error)
	CountSessionsByStatus(ctx context.Context, status string) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateToolExecution(ctx context.Context, arg CreateToolExecutionParams) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteMessagesBySession(ctx context.Context, sessionID string) error
	DeleteMetadata(ctx context.Context, key string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteToolExecution(ctx context.Context, id string) error
	DeleteToolExecutionsByMessage(ctx context.Context, messageID string) error
	GetConversationThread(ctx context.Context, id string) ([]GetConversationThreadRow, error)
	GetFailedToolExecutions(ctx context.Context, arg GetFailedToolExecutionsParams) ([]ToolExecution, error)
	GetLatestMessage(ctx context.Context, sessionID string) (Message, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetMessageCount(ctx context.Context, sessionID string) (int64, error)
	GetMessageCountByRole(ctx context.Context, arg GetMessageCountByRoleParams) (int64, error)
	GetMessagesByTimeRange(ctx context.Context, arg GetMessagesByTimeRangeParams) ([]Message, error)
	GetMetadata(ctx context.Context, key string) (Metadata, error)
	GetPendingToolExecutions(ctx context.Context) ([]ToolExecution, error)
	GetRecentToolExecutions(ctx context.Context, limit int64) ([]ToolExecution, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionWithMessageCount(ctx context.Context, id string) (GetSessionWithMessageCountRow, error)
	GetToolExecution(ctx context.Context, id string) (ToolExecution, error)
	GetToolExecutionCount(ctx context.Context, messageID string) (int64, error)
	GetToolExecutionCountByStatus(ctx context.Context, status string) (int64, error)
	GetToolExecutionStats(ctx context.Context, toolName string) (GetToolExecutionStatsRow, error)
	GetToolExecutionsByTimeRange(ctx context.Context, arg GetToolExecutionsByTimeRangeParams) ([]ToolExecution, error)
	GetToolUsageStats(ctx context.Context) ([]GetToolUsageStatsRow, error)
	GetTotalTokensUsed(ctx context.Context, sessionID string) (interface{}, error)
	HardDeleteSession(ctx context.Context, id string) error
	IncrementRetryCount(ctx context.Context, id string) error
	ListAllSessions(ctx context.Context) ([]Session, error)
	ListMessagesByParent(ctx context.Context, parentID *string) ([]Message, error)
	ListMessagesByRole(ctx context.Context, arg ListMessagesByRoleParams) ([]Message, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListMessagesBySessionPaginated(ctx context.Context, arg ListMessagesBySessionPaginatedParams) ([]Message, error)
	ListMetadata(ctx context.Context) ([]Metadata, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error)
	ListToolExecutionsByMessage(ctx context.Context, messageID string) ([]ToolExecution, error)
	ListToolExecutionsByName(ctx context.Context, arg ListToolExecutionsByNameParams) ([]ToolExecution, error)
	ListToolExecutionsBySession(ctx context.Context, arg ListToolExecutionsBySessionParams) ([]ToolExecution, error)
	ListToolExecutionsByStatus(ctx context.Context, arg ListToolExecutionsByStatusParams) ([]ToolExecution, error)
	MetadataExists(ctx context.Context, key string) (bool, error)
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]Message, error)
	SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error)
	SetMetadata(ctx context.Context, arg SetMetadataParams) error
	TouchSession(ctx context.Context, id string) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpdateToolExecutionError(ctx context.Context, arg UpdateToolExecutionErrorParams) error
	UpdateToolExecutionOutput(ctx context.Context, arg UpdateToolExecutionOutputParams) error
	UpdateToolExecutionStatus(ctx context.Context, arg UpdateToolExecutionStatusParams) error
}

var _ Querier = (*Queries)(nil)
