// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package database

import (
	"context"
)

const archiveSession = `-- name: ArchiveSession :exec
UPDATE sessions
SET status = 'archived'
WHERE id = ?
`

func (q *Queries) ArchiveSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, archiveSession, id)
	return err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) as count
FROM sessions
WHERE status != 'deleted'
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByStatus = `-- name: CountSessionsByStatus :one
SELECT COUNT(*) as count
FROM sessions
WHERE status = ?
`

func (q *Queries) CountSessionsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, name, status, model, temperature, max_tokens, settings
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateSessionParams struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Status      string   `json:"status"`
	Model       *string  `json:"model"`
	Temperature *float64 `json:"temperature"`
	MaxTokens   *int64   `json:"max_tokens"`
	Settings    *string  `json:"settings"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Model,
		arg.Temperature,
		arg.MaxTokens,
		arg.Settings,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE sessions
SET status = 'deleted'
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
WHERE id = ? AND status != 'deleted'
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.Settings,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.Settings,
	)
	return i, err
}

const getSessionWithMessageCount = `-- name: GetSessionWithMessageCount :one
SELECT
    s.id,
    s.name,
    s.created_at,
    s.updated_at,
    s.status,
    s.model,
    s.temperature,
    s.max_tokens,
    s.settings,
    COUNT(m.id) as message_count
FROM sessions s
LEFT JOIN messages m ON s.id = m.session_id
WHERE s.id = ? AND s.status != 'deleted'
GROUP BY s.id
`

type GetSessionWithMessageCountRow struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	CreatedAt    string   `json:"created_at"`
	UpdatedAt    string   `json:"updated_at"`
	Status       string   `json:"status"`
	Model        *string  `json:"model"`
	Temperature  *float64 `json:"temperature"`
	MaxTokens    *int64   `json:"max_tokens"`
	Settings     *string  `json:"settings"`
	MessageCount int64    `json:"message_count"`
}

func (q *Queries) GetSessionWithMessageCount(ctx context.Context, id string) (GetSessionWithMessageCountRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithMessageCount, id)
	var i GetSessionWithMessageCountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.Settings,
		&i.MessageCount,
	)
	return i, err
}

const hardDeleteSession = `-- name: HardDeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) HardDeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteSession, id)
	return err
}

const listAllSessions = `-- name: ListAllSessions :many
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListAllSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listAllSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
WHERE status != 'deleted'
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByStatus = `-- name: ListSessionsByStatus :many
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
WHERE status = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsByStatusParams struct {
	Status string `json:"status"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessions = `-- name: SearchSessions :many
SELECT id, name, created_at, updated_at, status, model, temperature, max_tokens, settings
FROM sessions
WHERE status != 'deleted'
  AND (name LIKE ? OR id LIKE ?)
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type SearchSessionsParams struct {
	Name   string `json:"name"`
	ID     string `json:"id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, searchSessions,
		arg.Name,
		arg.ID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET name = ?,
    model = ?,
    temperature = ?,
    max_tokens = ?,
    settings = ?
WHERE id = ? AND status != 'deleted'
`

type UpdateSessionParams struct {
	Name        string   `json:"name"`
	Model       *string  `json:"model"`
	Temperature *float64 `json:"temperature"`
	MaxTokens   *int64   `json:"max_tokens"`
	Settings    *string  `json:"settings"`
	ID          string   `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Name,
		arg.Model,
		arg.Temperature,
		arg.MaxTokens,
		arg.Settings,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions
SET status = ?
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}
